### ISSUE TITLE
placeholderapi support

### ISSUE THREAD

**Issue by lifeofguenter** [Earth2b2t/AnarchyChat#1]
would be great :)

**Comment by Toshimichi0915** [comment]
What do you think should be added as place holder?
I can add ignore list and mute list as place holders, but I don't see the point of these placeholders.

Also, make sure to update to version 1.0.1

**Comment by lifeofguenter** [comment]
I think to start with it would be great to support placeholderapi (https://github.com/PlaceholderAPI/PlaceholderAPI) in the message formatting.

That way plugin users can format messages based on player ranks (set by a different plugin).

Since it is widely used, it means also this will work well with many other plugins.

**Comment by Toshimichi0915** [comment]
If you are talking about global chat, AnarchyChat doesn't modify anything.

This plugin only adds /ignore command and /tell, /mute functionality.
If you want to show player ranks, you can use third-party chat plugins that support PlaceHolderAPI.

However, global message customization and PlaceHolderAPI will be nice if added. I will definitely add these features later!

**Comment by lifeofguenter** [comment]
> However, global message customization and PlaceHolderAPI will be nice if added. I will definitely add these features later!

Yes exactly just this :) - well and also pm customization

I sent you an email around this :)
